name: Spell Check and Auto-Fix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  autofix:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Allows push access for github-actions bot

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install codespell
        run: pip install codespell

      - name: Auto-correct typos in notes.md
        run: |
          codespell --write-changes notes.md
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add notes.md
          git commit -m "Auto-fix typos in notes.md" || echo "No changes to commit"
          git push
